server:
  port: 8110
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.92.0.112:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-member
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
  session:
    store-type: redis
  redis:
    host: 47.92.0.112
    port: 6379
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
    sender:
      type: web

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true