server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 47.92.0.112
  session:
    store-type: redis

gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

