server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 47.92.0.112
  session:
    store-type: redis
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
    sender:
      type: web

gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true