server:
  port: 20000
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.137.204:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 139.224.137.204

