server:
  port: 20000
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.105.74:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 47.100.105.74

