server:
  port: 25000
spring:
  application:
    name: gulimall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        port: 8791
        dashboard: localhost:8333
  redis:
    host: 47.92.0.112
    port: 6379

  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        core-size: 5
        max-size: 20
  session:
    store-type: redis
  rabbitmq:
    host: 47.92.0.112
    virtual-host: /
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: '*'