server:
  port: 9000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.92.0.112:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
  sentinel:
    transport:
      dashboard: localhost:8333

  rabbitmq:
    host: 47.92.0.112
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 47.92.0.112
    port: 6379
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

# feign调用超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

alipay:
  app_id: 2021000121644268
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDqXgZ5Rk9YrUlTHcgMRzci04K+N13ah3DEocDSofWGSHpK7y3PFXiYgirEvWE1ZVVeMc6HJmapW/3AHC9TIgE+pkI7UEBnayiZbvBF6X9oGeqbLemceUXBy4Ce6/gg2wSirAATXCotTvdxO+Z7b89P7wP+6vt6UAgwGj0/p1TSdil43Hu2VDv5t+EZiJJwraoaS1pZVZ+NAjbONHvAQwfHQSDu7vwplhvaQVC/FI63WTlCu3wmzF9U5TWoZLMejOaw2Uo8W7FQyzvsd0ReYeB5xdXMuCP5KVGEk1cse0CXy26dadl/xKwvLkfnW9Kc7Kb246JFMpZKKNqKHhOWrKLAgMBAAECggEAFLwDxzK4/wFT0vUMdrPdrB1zEsSWq43qQ37WIeonBPA64LvKztws+cWLx51FuWLs5VbcPfND79hySgmY6OaQT37C8ug5iFNONRN01xyLcZorAittNs1BCrSvEoJK/A7RSBG8XvvV4Xr7MiAph/Vi27nCUytHZ/nc2tupA7VrtKSiJ+Kv36vi580c8PS0REhqMmt96tzDTFsYT1kEWJyiaZYuU8vR3Vmlrl3DtxRU8T5X495fNngb66uzejhWjVa4BEAUANRMO7I3r+XVN0S4uj8tWMr1s4Se6V5an7GVrOqUZ+PnEKOh5T23+IohvNrUIxkYP8twJCNNX5NV6iZwcQKBgQDxXJj7RwMFLA2krP/XRaZfzYHIKt1vQ14WuK4X6bAnB79gkmvVxkkqO1jYmjiEBmOUcn4fs4B7Aso0dAZlIodPScihboJ8koLyWFUhZuU0kWK0Ile35euWceo5Cro3mRR/isAmVsUHvluvQdiG9Qgu5y1kgAYVs98oEBWV5s+FYwKBgQDPh1V0+9C+21QPdBJ2echtA8HlNnhXioPLfPyjeblSQ/uOaqc8REIpAWZQ01/f1xikwmGjaXki7pbTSLMcDmKax5hMojRfH3S5Kvi5j78xi2kphSDO2lKdTA5G5ExdZ87QvqUQ1Z/Cch3oIP/8UBdS+mmzT1ztWoQ4Mg2rPg/auQKBgQC2AlsG2kUHyHG9ZgxEPSy6gBHHbbOwbL/uKHR4aexBcpE59RDGk5Gm/DwCk0HdJahAUJqVs1pG6RKsvXX5HDGnc/+M5PYXlLCUqlIAL0TXAG/LYT5+2i5vNBYpz9IfjRutFmfSQYqxTTZ8kg4Dr5HtNL3BVN3BzfORlZeBhB2n+wKBgF2HQJxYYNujPV85kJiUih+Xces7gUDyzDMJQVLrqPnKabTlnDktCiQw3UvP94WKCzE16YscHdwAazkNqqsaUJYxHhJrh+7W3mQVWcNHZYOOsPZlaUPQYStC+6w3d7Mg9bReN0Y/AKFBjPjw5m1wKxLaiIinW9oc0ToCVOa4Ma0BAoGAZWhUq0w2HX6mcIuvjJ4x1WaWh+IjD8hqRUoWfp0GayaNi0fhA5eCC1d/MO41CnALnEBzxsEV3VKfzQdruUo9z+IDAAG6kTBpLDEIxwIWQmSp1gmMNa3dyNhjp7+E6wPOMX6EmTlJe1NnZK+1haKPjbqMMUPkgjThJIwJ0qJKViA=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi54sbb7c3wx8D9pbqhuAALYTrEN7/SSc0sKW1zIyPfVWNd5axCND6WrD1lRhHJzYTy+qG+SVQxKbVZlzlrRx8QVAoXZ+DogW67GDm+cpRFVxALOq6jdQbS4lT0oTSSl8XHKyVAGCdWZceaU+RNPjFwF15Go/sNnO/dpaWuCgpFnvd6gfZnTPKQb/52Kr+4rdUorJVtTVmHmw3F877rEhm64/NUiBkBRa4nVnzCDx+pCBB4spIfCSOf6G6jhGzcaobYFeoopIPPoaRtRd37x1BjkoNdk+BF7AasB4kk/tBC1bAS5KZQHG0i4qEgSq7XvkaYeB3IVlNlolUTHlSvYZCwIDAQAB
  notify_url: https://342296y03l.zicp.fun/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

management:
  endpoints:
    web:
      exposure:
        include: *