server:
  port: 9000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.100.105.74:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.105.74:8848
  rabbitmq:
    host: 47.100.105.74
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 47.100.105.74
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

# feign调用超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000


