server:
  port: 12000
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 111.67.194.232:8848
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
