server:
  port: 13005
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

management:
  endpoints:
    web:
      exposure:
        include: *