server:
  port: 12000
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 139.224.137.204:8848
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
