server:
  port: 13005
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
