spring:
  cloud:
    gateway:
      routes:
        - id: admin_ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/index/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: gulimall_product_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com
        - id: gulimall_search_host_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
        - id: gulimall_auth_server_host_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com
        - id: gulimall_seckill_route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
    sender:
      type: web
