spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    alicloud:
      access-key: LTAI5t6NA1MMjbB7EGKKXAAW
      secret-key: docTpuRoFxjo1SSOA8t4MwO6gopcw5
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
        bucket: gulimall-518
      sms:
        accessKeyId: "LTAI5t9hgU42BZaKWbtm9fqD"
        accessKeySecret: "BV4YJzHoSbmV6uE4JXMlx4QYdqVwHm"
        endpoint: "dysmsapi.aliyuncs.com"
        signName: "阿里云短信测试"
        templateCode: "SMS_154950909"
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
    sender:
      type: web
server:
  port: 30000

logging:
  level:
    com.wz.gulimall.thirdparty: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true