server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 47.92.0.112:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  redis:
    host: 47.92.0.112
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
    sender:
      type: web

gulimall:
  thread:
    coreSize: 20
    maxSize: 50
    keepAliveTime: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true


